### ISSUE TITLE
"Codensity is not defined" in Codensity Transformer Monoid

### ISSUE THREAD

**Issue by willheslam** [mattbierner/akh-codensity#1]
I was experimenting with this (potentially nonsensical operation):
```
const State = require('akh').State

State.of('a').concat(State.of('b')).run('c')
```

and got:
```
ReferenceError: Codensity is not defined
    at Object.k [as f] (/project/node_modules/akh.codensity/trans/codensity.js:37:22)
```

which is occurring here:
```
    spec.Monoid(Instance,
        new Instance(_ => m.zero),

        function (b) {
            return new Instance(k =>
                Codensity.runCodensity(this, k)
                    .concat(Codensity.runCodensity(b, k)))
        })
```
in file
https://github.com/mattbierner/akh-codensity/blob/master/trans/codensity.js

I can't say I understand exactly what a codensity is yet (need to work my way through https://www.maths.ed.ac.uk/~tl/sydney/sydney_talk.pdf !) but is `Codensity` expected to be a value here?
Unless this code relies on `Codensity` being somehow available in the global scope (which to my understanding wouldn't be true in strict mode, for example), this looks like it'll always throw this exception, regardless of the validity of the instigating code.

Maybe I'm missing something, but does this work as intended, or is it a bug to reference `Codensity` without requiring it?

**Comment by mattbierner** [comment]
Yeah that code is definitely wrong. A few observations:

1. I don't know if `State.concat` is valid? You can have something like `StateT(List)` and then do `.concat`  but I don't think there's anything you can do for plain old `State`?

2. I'll changed the codensity code to:

    ```ts
    spec.Monoid(Instance,
        new Instance(_ => m.zero),

        function (b) {
            return new Instance(k =>
                CodensityT.run(this, k)
                    .concat(CodensityT.run(b, k)))
        })
    ```

But I am not entirely sure that's correct? Also it will probably explode the stack with some call patterns. It does at least let you run:

```js
const StateT = require('akh.state').StateT
const List = require('akh.list').List

const M = StateT(List);
const run = (c, state) => List.run(StateT.run(c, state))

run(M.of(1).concat(M.of(2)), 'state')  === [ { value: 1, state: 'state' }, { value: 2, state: 'state' } ]
```

**Comment by willheslam** [comment]
@mattbierner Thanks for the prompt response and fix!

Sorry, you're right - here's the context around what I was trying to do:
```
const { StateT } = require('akh.state')
const { Either } = require('akh.either')

const M = StateT(Either)

const run = (c, state) => Either.run(StateT.run(c, state))

const start =
  M.of('bar')
    .chain(
      x => M.modify(state => state.toUpperCase()).concat(M.of(x))
    )

console.log(run(start, 'foo'))
```

where I was expecting `.concat(M.of(x))` to be identical to to `.map(() => x)` or `.chain(() => M.of(x))`

With the old version I get:
`ReferenceError: Codensity is not defined`

With the new version 0.0.2 for akh-state with the fix above, I get:
`{ right: true, value: { value: 'FOO', state: 'FOO' } }`
as opposed to what I was hoping, which was:
`{ right: true, value: { value: 'bar', state: 'FOO' } }`

but that perhaps stems from my misunderstanding of what concat means in this context.
I wonder what it actually does though - looks like a no op!

As predicted,
```
x => M.modify(state => state.toUpperCase()).chain(() => M.of(x))
```
gets me exactly what I expected `.concat` would do.
